In [1]:
#Q2. Row Echelon Form: 
#Create a 5x5 matrix, A, with entries randomly chosen integers between 0 and 9. To generate the 
#random matrix, set the random seed as the last two digits of your roll number. Reduce matrix A to its 
#Row Echelon Form by performing elementary row operations. 

In [2]:
import numpy as np
# Set the random seed based on the last two digits of your roll number
np.random.seed(36)  # You can replace 36 with your own last two digits

# Create a 5x5 matrix A with random integers between 0 and 9
A = np.random.randint(0, 10, (5, 5))
print("Original Matrix A:")
print(A)

# Perform elementary row operations to reduce A to its row echelon form
for i in range(min(A.shape)):
    # Find the pivot element in column i
    pivot_idx = np.argmax(A[i:, i]) + i
    A[[i, pivot_idx]] = A[[pivot_idx, i]]  # Swap rows to move the pivot to the diagonal position
    pivot_row = A[i, i]
    if pivot_row != 0:
        A[i] = A[i] / pivot_row  # Make the pivot element 1
        for j in range(i + 1, A.shape[0]):
            A[j] -= A[j, i] * A[i]  # Make the elements below the pivot zero
print("\nRow Echelon Form of Matrix A:")
print(A)

Original Matrix A:
[[3 0 5 3 4]
 [9 8 1 5 9]
 [6 8 7 8 5]
 [2 8 1 6 4]
 [8 4 6 4 9]]

Row Echelon Form of Matrix A:
[[1 0 0 0 1]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
