In [1]:
#Q3. Singular Value Decomposition (SVD): 
#Perform Singular Value Decomposition on the matrix A obtained in Question 2. Separate and print 
#matrices U, Σ, and 𝑉 .Verify that A equals the product of U, Σ, and 𝑉.Additionally, find the rank 2 
#and rank 3 approximations of matrix A. 

In [3]:
import numpy as np
# Define the matrix A (use the matrix A obtained from Question 2)
A = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 6],
    [3, 4, 5, 6, 7],
    [4, 5, 6, 7, 8],
    [5, 6, 7, 8, 9]
])
# Perform Singular Value Decomposition (SVD)
U, Sigma, V_transpose = np.linalg.svd(A)
# Print matrices U, Sigma, and V_transpose
print("Matrix U:")
print(U)
print("\nMatrix Sigma (Diagonal Matrix):")
print(np.diag(Sigma))
print("\nMatrix V Transpose:")
print(V_transpose)
# Verify that A equals the product of U, Sigma, and V_transpose
A_reconstructed = np.dot(U, np.dot(np.diag(Sigma), V_transpose))
print("\nReconstructed Matrix A:")
print(A_reconstructed)
# Find the rank 2 and rank 3 approximations of matrix A
rank_2_approx = np.dot(U[:, :2], np.dot(np.diag(Sigma[:2]), V_transpose[:2, :]))
rank_3_approx = np.dot(U[:, :3], np.dot(np.diag(Sigma[:3]), V_transpose[:3, :]))
print("\nRank 2 Approximation of Matrix A:")
print(rank_2_approx)
print("\nRank 3 Approximation of Matrix A:")
print(rank_3_approx)

Matrix U:
[[-0.27147568 -0.72546602  0.6268527  -0.06315811  0.05537826]
 [-0.35197777 -0.41965658 -0.6942296  -0.45104272  0.12085415]
 [-0.43247986 -0.11384714 -0.2440318   0.85176966  0.12221675]
 [-0.51298195  0.1919623   0.06334162 -0.09777873 -0.828509  ]
 [-0.59348403  0.49777174  0.24806708 -0.2397901   0.53005983]]

Matrix Sigma (Diagonal Matrix):
[[2.68614066e+01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 1.86140662e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.20304281e-15 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 2.23702686e-16
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  5.81885606e-17]]

Matrix V Transpose:
[[-0.27147568 -0.35197777 -0.43247986 -0.51298195 -0.59348403]
 [ 0.72546602  0.41965658  0.11384714 -0.1919623  -0.49777174]
 [ 0.32258797 -0.6508131   0.02443455  0.61321833 -0.30942775]
 [ 0.54079038 -0.38992945 -0.2